# Generated by Django 4.0.1 on 2022-07-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_social_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
